import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  doublePrecision,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// principal_object — shared base class for Person, Property, Paperwork
// ---------------------------------------------------------------------------
//
// Every Person, Property and Paperwork row has exactly one corresponding
// principal_object row. The code (e.g. PERS00001, PROP00002) lives here and
// is generated from a single shared Postgres sequence
// (`principal_object_code_seq`), so numbers are unique across all three types.
//
// The sequence is created in the migration (not expressible in Drizzle).
// The code is NOT auto-generated by a DEFAULT — the application layer inserts
// this row first (supplying code via a sql`` nextval expression), then inserts
// the domain row with the returned id and code value.

export const principalObjectTypeEnum = pgEnum("principal_object_type", [
  "PERSON",
  "PROPERTY",
  "PAPERWORK",
]);

export const principalObject = pgTable("principal_object", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Full code including prefix, e.g. "PERS00003". Supplied by app layer.
  code: text("code").notNull().unique(),
  objectType: principalObjectTypeEnum("object_type").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// NOTE: `integer` is used below for sort_order on the lookup tables.

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const personTypeEnum = pgEnum("person_type", ["NATURAL", "JUDICIAL"]);

export const addressKindEnum = pgEnum("address_kind", [
  "HOME",
  "POSTAL",
  "HEADQUARTERS",
  "CORRESPONDENCE",
]);

export const idDocumentTypeEnum = pgEnum("id_document_type", [
  "ID_CARD",
  "PASSPORT",
]);

export const genderEnum = pgEnum("gender", ["MALE", "FEMALE"]);

// Judicial-person legal/organisational form. Fixed list for now; new values
// require a migration. SRL/SA/PFA/etc. are Romanian company-form codes.
export const judicialTypeEnum = pgEnum("judicial_type", [
  "SRL",
  "SA",
  "SRL_D",
  "PFA",
  "II",
  "IF",
  "ONG",
  "OTHER",
]);

// ---------------------------------------------------------------------------
// person — base / supertype
// ---------------------------------------------------------------------------
//
// Holds everything true of any person (natural or judicial). All M:M junction
// tables FK to `person.id` and never need to know the subtype.

export const person = pgTable("person", {
  id: uuid("id").primaryKey().defaultRandom(),

  // FK to the shared principal_object row that owns this person's code.
  // Set at creation; never changes.
  principalObjectId: uuid("principal_object_id")
    .notNull()
    .unique()
    .references(() => principalObject.id),

  // Human-readable code like "PERS00001". Copied from principal_object.code
  // at creation time. No DEFAULT — supplied by the app layer (see queries.ts).
  code: text("code").notNull().unique(),

  type: personTypeEnum("type").notNull(),

  // Cached display name — populated by API code on insert/update from the
  // subtype (first_name + last_name for natural; company name for judicial
  // when that lands in Slice #1.5). Used by the list view and search.
  displayName: text("display_name").notNull(),

  notes: text("notes"),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// natural_person — subtype for humans
// ---------------------------------------------------------------------------
//
// 1:1 with `person`. PK is also FK to person.id with ON DELETE CASCADE so
// hard-deleting a person also removes the satellite row. Soft delete (the
// API path) just sets person.deleted_at and leaves this row untouched.

export const naturalPerson = pgTable(
  "natural_person",
  {
    personId: uuid("person_id")
      .primaryKey()
      .references(() => person.id, { onDelete: "cascade" }),

    firstName: text("first_name"),
    lastName: text("last_name"),
    nickname: text("nickname"),

    // CNP — Romanian Personal Numeric Code. Optional (foreign nationals
    // may not have one). UNIQUE when present (partial unique index below).
    // Once set, cannot be changed — enforced by a trigger added in the
    // migration (NULL -> value is allowed; value -> anything-different is not).
    cnp: text("cnp"),

    idDocumentType: idDocumentTypeEnum("id_document_type"),
    idDocumentNumber: text("id_document_number"),

    gender: genderEnum("gender"),
    // `mode: "string"` keeps DOB as ISO date strings ("1985-02-03") on both
    // read and write — avoids the Date-object timezone gotcha for a calendar
    // date with no time component.
    dateOfBirth: date("date_of_birth", { mode: "string" }),

    personalPhone1: text("personal_phone_1"),
    personalPhone2: text("personal_phone_2"),
    workPhone: text("work_phone"),
    personalEmail1: text("personal_email_1"),
    personalEmail2: text("personal_email_2"),
    workEmail: text("work_email"),
  },
  (t) => [
    // At least one of first_name / last_name must be set.
    check(
      "natural_person_has_name",
      sql`${t.firstName} IS NOT NULL OR ${t.lastName} IS NOT NULL`,
    ),
    // ID document type and number are paired — both set or both null.
    check(
      "natural_person_id_doc_paired",
      sql`(${t.idDocumentType} IS NULL) = (${t.idDocumentNumber} IS NULL)`,
    ),
    // At least one contact method (any phone or email) must be set.
    check(
      "natural_person_has_contact",
      sql`coalesce(${t.personalPhone1}, ${t.personalPhone2}, ${t.workPhone}, ${t.personalEmail1}, ${t.personalEmail2}, ${t.workEmail}) IS NOT NULL`,
    ),
    // CNP is unique when present (partial unique index).
    uniqueIndex("natural_person_cnp_unique")
      .on(t.cnp)
      .where(sql`${t.cnp} IS NOT NULL`),
  ],
);

// ---------------------------------------------------------------------------
// judicial_person — subtype for organisations / legal entities
// ---------------------------------------------------------------------------
//
// 1:1 with `person`. PK is also FK to person.id with ON DELETE CASCADE so
// hard-deleting a person also removes the satellite row. Soft delete (the
// API path) just sets person.deleted_at and leaves this row untouched.
//
// `notes` lives on the parent `person` row (same as natural_person).
// HEADQUARTERS + CORRESPONDENCE addresses are stored in the existing
// `address` table; both kinds already exist in addressKindEnum.

export const judicialPerson = pgTable(
  "judicial_person",
  {
    personId: uuid("person_id")
      .primaryKey()
      .references(() => person.id, { onDelete: "cascade" }),

    // Display / legal name. Required.
    name: text("name").notNull(),
    nickname: text("nickname"),

    judicialType: judicialTypeEnum("judicial_type"),

    // CUI — Cod Unic de Inregistrare (Romanian fiscal registration code).
    // Optional. UNIQUE when present (partial unique index below).
    // Once set, cannot be changed — enforced by a trigger added in the
    // migration (NULL -> value is allowed; value -> anything-different is not).
    cuiNumber: text("cui_number"),

    // Trade Register number — "Nr. ORC" (e.g. "J22/123/2020").
    tradeRegisterNumber: text("trade_register_number"),

    // Contact persons — temporary free-text placeholders.
    // → Future slice will replace with M:M to Person.
    contactPerson1: text("contact_person_1"),
    contactPerson2: text("contact_person_2"),
  },
  (t) => [
    // CUI is unique when present (partial unique index).
    uniqueIndex("judicial_person_cui_unique")
      .on(t.cuiNumber)
      .where(sql`${t.cuiNumber} IS NOT NULL`),
  ],
);

// ---------------------------------------------------------------------------
// address — owned by a person, one row per (person, kind)
// ---------------------------------------------------------------------------
//
// FK cascades on hard-delete of person. When a user clears an address block
// in the form, we hard-delete the row directly (no deleted_at on address —
// addresses are part of the person's aggregate, not separately archived).

export const address = pgTable(
  "address",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    personId: uuid("person_id")
      .notNull()
      .references(() => person.id, { onDelete: "cascade" }),

    kind: addressKindEnum("kind").notNull(),

    // "Street, No., Block, Floor, Apt" — single free-form field per spec.
    streetLine: text("street_line"),
    postalCode: text("postal_code"),
    // "City, Locality, UAT, Commune, Village" — single free-form field.
    locality: text("locality"),
    // "County / Sector" — free text for now; will become FK later.
    county: text("county"),
    country: text("country").notNull(),
    notes: text("notes"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // A person can have at most one address of each kind.
    uniqueIndex("address_person_kind_unique").on(t.personId, t.kind),
  ],
);

// ---------------------------------------------------------------------------
// Enums — Property domain
// ---------------------------------------------------------------------------

export const propertyTypeEnum = pgEnum("property_type", ["LAND"]);

// Placeholder values; will be replaced with real ANCPI categories later.
export const propertyCategoryEnum = pgEnum("use_category", [
  "CATEG1",
  "CATEG2",
  "CATEG3",
]);

// ---------------------------------------------------------------------------
// property — root entity
// ---------------------------------------------------------------------------
//
// Soft-delete via deleted_at (same pattern as person).
// Code is auto-generated from a Postgres sequence: PROP00001, PROP00002, ...
// The sequence is created in the migration (not expressible in Drizzle).

export const property = pgTable("property", {
  id: uuid("id").primaryKey().defaultRandom(),

  // FK to the shared principal_object row that owns this property's code.
  principalObjectId: uuid("principal_object_id")
    .notNull()
    .unique()
    .references(() => principalObject.id),

  // Human-readable code like "PROP00002". Copied from principal_object.code
  // at creation time. No DEFAULT — supplied by the app layer.
  code: text("code").notNull().unique(),

  type: propertyTypeEnum("type").notNull().default("LAND"),

  // "Porecla / elemente definitorii" — short identifying label.
  nickname: text("nickname"),

  // Romanian cadastral identifiers.
  tarlaSola:       text("tarla_sola"),       // Nr. tarla / sola
  parcela:         text("parcela"),           // Nr. parcela
  cadastralNumber: text("cadastral_number"),  // Nr. cadastru
  carteFunciara:   text("carte_funciara"),    // Nr. carte funciara

  useCategory: propertyCategoryEnum("use_category"),

  // "Suprafata in mp" — area in square metres.
  surfaceAreaMp: numeric("surface_area_mp", { precision: 12, scale: 2 }),

  notes: text("notes"),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// property_address — single address block per property
// ---------------------------------------------------------------------------
//
// FK cascades on hard-delete of property. No `kind` column — a property has
// exactly one address. No deleted_at — clearing the address hard-deletes the
// row (same pattern as Person address).

export const propertyAddress = pgTable(
  "property_address",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    streetLine: text("street_line"),
    postalCode: text("postal_code"),
    locality:   text("locality"),
    county:     text("county"),
    country:    text("country").notNull(),
    notes:      text("notes"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Each property has at most one address row.
    uniqueIndex("property_address_property_unique").on(t.propertyId),
  ],
);

// ---------------------------------------------------------------------------
// property_corner — ordered polygon vertices, stored as WGS84 decimal degrees
// ---------------------------------------------------------------------------
//
// Corners are the authoritative geometry. The polygon for map display is
// derived from the ordered corner set at query time. Heights are omitted —
// we store 2-D planimetric coordinates only.

export const propertyCorner = pgTable(
  "property_corner",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    // 1-based display order; unique per property.
    sequenceNo: integer("sequence_no").notNull(),

    // WGS84 / ETRS89 decimal degrees.
    lat: doublePrecision("lat").notNull(),
    lon: doublePrecision("lon").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("property_corner_property_seq_unique").on(
      t.propertyId,
      t.sequenceNo,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Lookup / Reference-Data tables  (Slice #3 — Liste de Valori)
// ---------------------------------------------------------------------------
//
// These tables back the admin "Value Lists" screen. They are intentionally
// decoupled from the pg enums already in the schema (propertyTypeEnum,
// useCategoryEnum) — the enum→FK migration will happen in a later slice
// once the full domain model is settled.
//
// All tables share the same shape: uuid PK, payload fields, sort_order,
// created_at / updated_at (touched by the touch_updated_at trigger).

// ── Proprietate group ───────────────────────────────────────────────────────

export const lookupPropertyType = pgTable("lookup_property_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupTarla = pgTable("lookup_tarla", {
  id:        uuid("id").primaryKey().defaultRandom(),
  indicativ: text("indicativ").notNull(),
  descriere: text("descriere"),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupUseCategory = pgTable("lookup_use_category", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── Persoană group ──────────────────────────────────────────────────────────

export const lookupPersonType = pgTable("lookup_person_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupPersonRole = pgTable("lookup_person_role", {
  id:          uuid("id").primaryKey().defaultRandom(),
  name:        text("name").notNull(),
  description: text("description"),
  sortOrder:   integer("sort_order").notNull().default(0),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupCitizenship = pgTable("lookup_citizenship", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── Document group ──────────────────────────────────────────────────────────

export const lookupDocumentType = pgTable("lookup_document_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupInstitution = pgTable("lookup_institution", {
  id:              uuid("id").primaryKey().defaultRandom(),
  name:            text("name").notNull(),
  institutionType: text("institution_type"),
  sortOrder:       integer("sort_order").notNull().default(0),
  createdAt:       timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:       timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── Document Type ↔ Person Role junction ────────────────────────────────────
//
// Managed via the "Document Persons" admin panel. Both FKs cascade on delete
// so removing a document type or person role automatically cleans up associations.

export const lookupDocTypePersonRole = pgTable(
  "lookup_doc_type_person_role",
  {
    id:             uuid("id").primaryKey().defaultRandom(),
    documentTypeId: uuid("document_type_id")
      .notNull()
      .references(() => lookupDocumentType.id, { onDelete: "cascade" }),
    personRoleId:   uuid("person_role_id")
      .notNull()
      .references(() => lookupPersonRole.id, { onDelete: "cascade" }),
    createdAt:      timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("lookup_doc_type_person_role_unique").on(t.documentTypeId, t.personRoleId),
  ],
);

// ── Others (was lookup_service_interest, renamed in migration 011) ──────────
//
// General-purpose bucket for categorised lookup values that don't belong to
// Property / Person / Document. Current categories: Serviciu, Interes, Grup,
// Stampila. The `category` column is injected by the query layer; the UI only
// exposes the `name` field.

export const lookupOthers = pgTable("lookup_others", {
  id:          uuid("id").primaryKey().defaultRandom(),
  name:        text("name").notNull(),
  description: text("description"),
  category:    text("category"),
  sortOrder:   integer("sort_order").notNull().default(0),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Enums — Paperwork domain
// ---------------------------------------------------------------------------

export const paperworkTypeEnum = pgEnum("paperwork_type", [
  "ACT_ADJUDECARE",
  "ACT_CADASTRU",
  "ACT_DONATIE",
  "AUTORIZATIE",
  "AVIZ_INSTITUTIE",
  "CERTIFICAT_FISCAL",
  "CERTIFICAT_MOSTENITOR",
  "CERTIFICAT_SARCINI",
  "CERTIFICAT_URBANISM",
  "CONTRACT_ARENDA",
  "CONTRACT_INCHIRIERE",
  "CONTRACT_PARTAJ",
  "CONTRACT_PRESTARI_SERVICII",
  "CONTRACT_VANZARE",
  "EXTRAS_CARTE_FUNCIARA",
  "EXTRAS_PUG",
  "HOTARARE_JUDECATOREASCA",
  "TESTAMENT",
  "TITLU_PROPRIETATE",
]);

// ---------------------------------------------------------------------------
// paperwork — root entity
// ---------------------------------------------------------------------------
//
// Single-table design: all 19 document types share this table.
// Type-specific columns are nullable; the UI shows/hides them based on `type`.
//
// Columns marked "→ Slice 5" are temporary free-text placeholders that will
// be replaced by junction table relationships to Person in Slice 5.
//
// Code is auto-generated: PAPR00001, PAPR00002, …
// Soft-delete via deleted_at (same pattern as person / property).

export const paperwork = pgTable("paperwork", {
  id: uuid("id").primaryKey().defaultRandom(),

  // FK to the shared principal_object row that owns this document's code.
  principalObjectId: uuid("principal_object_id")
    .notNull()
    .unique()
    .references(() => principalObject.id),

  // Human-readable code like "PAPR00005". Copied from principal_object.code
  // at creation time. No DEFAULT — supplied by the app layer.
  code: text("code").notNull().unique(),

  type: paperworkTypeEnum("type").notNull(),

  // Short identifying label — the "Porecla" equivalent for paperwork.
  // e.g. "Vânzare Popescu 2021", "Titlu Teren Nord"
  title: text("title"),

  // ── Common fields (UI label varies by type) ────────────────────────────
  // "Nr. titlu / nr. certificat / nr. contract / nr. hotărâre / …"
  nrDocument:   text("nr_document"),
  // "Data autentificarii" / "Data eliberarii" / "Data emiterii"
  dateDocument: date("date_document", { mode: "string" }),
  // "Notariat" / "Institutie unde este inregistrat" / "Emitent" (generic)
  institution:  text("institution"),

  // ── Titlu de Proprietate specific ──────────────────────────────────────
  emitent:       text("emitent"),
  bazaLegala:    text("baza_legala"),
  uatProprietate: text("uat_proprietate"),
  uatProprietar:  text("uat_proprietar"),
  // Suprafata — numeric, same precision as property.surface_area_mp
  suprafata:     numeric("suprafata", { precision: 12, scale: 2 }),

  // ── Certificat de Moștenitor specific ─────────────────────────────────
  nrDosarSuccesoral: text("nr_dosar_succesoral"),
  dataDecesului:     date("data_decesului", { mode: "string" }),
  ultimulDomiciliu:  text("ultimul_domiciliu"),
  nrCertificatDeces: text("nr_certificat_deces"),

  // ── Contract de Închiriere specific ───────────────────────────────────
  dateStart: date("date_start", { mode: "string" }), // Data incepere contract
  dateEnd:   date("date_end",   { mode: "string" }), // Data incheierii valabilitate

  // ── Party placeholders (→ Slice 5 Person relationships) ───────────────
  // titularText : Titlu proprietate — Titular
  titularText:   text("titular_text"),
  // defunctText : Titlu proprietate / Certificat mostenitor — Defunct
  //               Testament — Testator
  defunctText:   text("defunct_text"),
  // partiesAText: Vanzatori / Proprietari / Donatori
  partiesAText:  text("parties_a_text"),
  // partiesBText: Cumparatori / Chiriasi / Donatari / Mostenitori
  partiesBText:  text("parties_b_text"),

  // ── Always present ─────────────────────────────────────────────────────
  notes: text("notes"), // Observatii

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// property_person — M:M junction between Property and Person  (Slice #5.1)
// ---------------------------------------------------------------------------
//
// No deleted_at — associations are hard-deleted (same pattern as address rows).
// ON DELETE CASCADE on both sides keeps this table clean automatically.
// Duplicate associations are blocked by the unique index.

export const propertyPerson = pgTable(
  "property_person",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    personId: uuid("person_id")
      .notNull()
      .references(() => person.id, { onDelete: "cascade" }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("property_person_unique").on(t.propertyId, t.personId),
  ],
);

// ---------------------------------------------------------------------------
// M:M junction tables  (Slice #5.1 + #5.2)
// ---------------------------------------------------------------------------

// property <-> paperwork  (Slice 5.2)
export const propertyPaperwork = pgTable(
  "property_paperwork",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    propertyId:  uuid("property_id").notNull().references(() => property.id,  { onDelete: "cascade" }),
    paperworkId: uuid("paperwork_id").notNull().references(() => paperwork.id, { onDelete: "cascade" }),
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("property_paperwork_unique").on(t.propertyId, t.paperworkId)],
);

// property <-> property  (self-ref, symmetric; id_a < id_b enforced by CHECK)
export const propertyProperty = pgTable(
  "property_property",
  {
    id:           uuid("id").primaryKey().defaultRandom(),
    propertyIdA:  uuid("property_id_a").notNull().references(() => property.id, { onDelete: "cascade" }),
    propertyIdB:  uuid("property_id_b").notNull().references(() => property.id, { onDelete: "cascade" }),
    createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("property_property_unique").on(t.propertyIdA, t.propertyIdB),
    check("property_property_order", sql`${t.propertyIdA} < ${t.propertyIdB}`),
  ],
);

// person <-> paperwork  (Slice 5.2)
export const personPaperwork = pgTable(
  "person_paperwork",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    personId:    uuid("person_id").notNull().references(() => person.id,      { onDelete: "cascade" }),
    paperworkId: uuid("paperwork_id").notNull().references(() => paperwork.id, { onDelete: "cascade" }),
    // Optional role tag — used by Certificat de Moștenitor.
    // 'DEFUNCT' = the deceased person; 'MOSTENITOR' = an inheritor.
    // NULL for persons linked via the general Persons tab on any doc type.
    quality:     text("quality"),
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("person_paperwork_unique").on(t.personId, t.paperworkId)],
);


// person <-> person  (self-ref, symmetric; id_a < id_b enforced by CHECK)
export const personPerson = pgTable(
  "person_person",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    personIdA:   uuid("person_id_a").notNull().references(() => person.id, { onDelete: "cascade" }),
    personIdB:   uuid("person_id_b").notNull().references(() => person.id, { onDelete: "cascade" }),
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("person_person_unique").on(t.personIdA, t.personIdB),
    check("person_person_order", sql`${t.personIdA} < ${t.personIdB}`),
  ],
);

// ---------------------------------------------------------------------------
// paperwork_page — uploaded file pages attached to a paperwork record
// ---------------------------------------------------------------------------
//
// One row per uploaded file. File is stored either on the local filesystem
// (development) or in Supabase Storage bucket "paperwork-pages" (production).
// `file_path` is the storage key in both cases.

export const paperworkPage = pgTable(
  "paperwork_page",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    paperworkId: uuid("paperwork_id")
      .notNull()
      .references(() => paperwork.id, { onDelete: "cascade" }),
    pageNumber:  integer("page_number").notNull(),
    pageName:    text("page_name"),
    pageNotes:   text("page_notes"),
    // Original filename as uploaded by the user, e.g. "scan001.pdf"
    fileName:    text("file_name").notNull(),
    // Storage path/key, e.g. "paperwork-pages/{paperworkId}/{pageId}.pdf"
    filePath:    text("file_path").notNull(),
    fileSize:    integer("file_size"),     // bytes
    mimeType:    text("mime_type"),
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt:   timestamp("updated_at",  { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("paperwork_page_paperwork_number_unique").on(
      t.paperworkId,
      t.pageNumber,
    ),
  ],
);

// paperwork <-> paperwork  (self-ref, symmetric; id_a < id_b enforced by CHECK)
export const paperworkPaperwork = pgTable(
  "paperwork_paperwork",
  {
    id:            uuid("id").primaryKey().defaultRandom(),
    paperworkIdA:  uuid("paperwork_id_a").notNull().references(() => paperwork.id, { onDelete: "cascade" }),
    paperworkIdB:  uuid("paperwork_id_b").notNull().references(() => paperwork.id, { onDelete: "cascade" }),
    createdAt:     timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("paperwork_paperwork_unique").on(t.paperworkIdA, t.paperworkIdB),
    check("paperwork_paperwork_order", sql`${t.paperworkIdA} < ${t.paperworkIdB}`),
  ],
);

// ---------------------------------------------------------------------------
// Auth — user_requests + app_users  (Slice #7.0)
// ---------------------------------------------------------------------------
//
// user_requests: staging table for sign-up applications.
//   status: pending → approved | rejected
//   No FK to app_users — admin reads and acts on requests independently.
//
// app_users: links a Supabase Auth UID to an app-level username + role.
//   supabase_uid is unique (one app record per auth identity).
//   username is unique.
//   role: "superuser" | "user"
//   approved_by: username of the admin who approved this account (null for
//   the seeded superuser).

export const userRequestStatusEnum = pgEnum("user_request_status", [
  "pending",
  "approved",
  "rejected",
]);

export const appUserRoleEnum = pgEnum("app_user_role", [
  "superuser",
  "user",
]);

export const userRequests = pgTable(
  "user_requests",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    email:       text("email").notNull(),
    username:    text("username").notNull(),
    status:      userRequestStatusEnum("status").notNull().default("pending"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    processedBy: text("processed_by"),   // username of the admin who acted
    // Store whether a welcome email was sent successfully
    emailSent:   boolean("email_sent").notNull().default(false),
  },
  (t) => [
    uniqueIndex("user_requests_email_pending_unique")
      .on(t.email)
      .where(sql`${t.status} = 'pending'`),
  ],
);

export const appUsers = pgTable(
  "app_users",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    // Supabase Auth user UUID — set when account is created via Admin API.
    // Null only for a brief window between request approval and account creation
    // (handled atomically, so in practice always set).
    supabaseUid: text("supabase_uid").unique(),
    email:       text("email").notNull().unique(),
    username:    text("username").notNull().unique(),
    role:        appUserRoleEnum("role").notNull().default("user"),
    approvedBy:  text("approved_by"),   // null for the seeded superuser
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
);
