import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  doublePrecision,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// principal_object — shared base class for Person, Property, Document
// ---------------------------------------------------------------------------
//
// Every Person, Property and Document row has exactly one corresponding
// principal_object row. The code (e.g. PERS00001, PROP00002) lives here and
// is generated from a single shared Postgres sequence
// (`principal_object_code_seq`), so numbers are unique across all three types.
//
// The sequence is created in the migration (not expressible in Drizzle).
// The code is NOT auto-generated by a DEFAULT — the application layer inserts
// this row first (supplying code via a sql`` nextval expression), then inserts
// the domain row with the returned id and code value.
//
// NOTE (Slice #15.05): the enum value was renamed from "PAPERWORK" to
// "DOCUMENT" — existing rows are migrated by migration_020_rename_to_document.sql.

export const principalObjectTypeEnum = pgEnum("principal_object_type", [
  "PERSON",
  "PROPERTY",
  "DOCUMENT",
]);

export const principalObject = pgTable("principal_object", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Full code including prefix, e.g. "PERS00003". Supplied by app layer.
  code: text("code").notNull().unique(),
  objectType: principalObjectTypeEnum("object_type").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// NOTE: `integer` is used below for sort_order on the lookup tables.

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const personTypeEnum = pgEnum("person_type", ["NATURAL", "JUDICIAL"]);

export const addressKindEnum = pgEnum("address_kind", [
  "HOME",
  "POSTAL",
  "HEADQUARTERS",
  "CORRESPONDENCE",
]);

export const idDocumentTypeEnum = pgEnum("id_document_type", [
  "ID_CARD",
  "PASSPORT",
]);

export const genderEnum = pgEnum("gender", ["MALE", "FEMALE"]);

// ---------------------------------------------------------------------------
// person — base / supertype
// ---------------------------------------------------------------------------
//
// Holds everything true of any person (natural or judicial). All M:M junction
// tables FK to `person.id` and never need to know the subtype.

export const person = pgTable("person", {
  id: uuid("id").primaryKey().defaultRandom(),

  // FK to the shared principal_object row that owns this person's code.
  // Set at creation; never changes.
  principalObjectId: uuid("principal_object_id")
    .notNull()
    .unique()
    .references(() => principalObject.id),

  // Human-readable code like "PERS00001". Copied from principal_object.code
  // at creation time. No DEFAULT — supplied by the app layer (see queries.ts).
  code: text("code").notNull().unique(),

  type: personTypeEnum("type").notNull(),

  // Cached display name — populated by API code on insert/update from the
  // subtype (first_name + last_name for natural; company name for judicial
  // when that lands in Slice #1.5). Used by the list view and search.
  displayName: text("display_name").notNull(),

  notes: text("notes"),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// natural_person — subtype for humans
// ---------------------------------------------------------------------------
//
// 1:1 with `person`. PK is also FK to person.id with ON DELETE CASCADE so
// hard-deleting a person also removes the satellite row. Soft delete (the
// API path) just sets person.deleted_at and leaves this row untouched.

export const naturalPerson = pgTable(
  "natural_person",
  {
    personId: uuid("person_id")
      .primaryKey()
      .references(() => person.id, { onDelete: "cascade" }),

    firstName: text("first_name"),
    lastName: text("last_name"),
    nickname: text("nickname"),

    // CNP — Romanian Personal Numeric Code. Optional (foreign nationals
    // may not have one). UNIQUE when present, but only among non-soft-deleted
    // persons — enforced by a trigger (migration_025), not a plain unique
    // index, since the partial index has no way to see person.deleted_at
    // (soft-delete lives on the parent `person` row). Once set, cannot be
    // changed — enforced by a separate trigger (NULL -> value is allowed;
    // value -> anything-different is not).
    cnp: text("cnp"),

    idDocumentType: idDocumentTypeEnum("id_document_type"),
    idDocumentNumber: text("id_document_number"),

    gender: genderEnum("gender"),
    // `mode: "string"` keeps DOB as ISO date strings ("1985-02-03") on both
    // read and write — avoids the Date-object timezone gotcha for a calendar
    // date with no time component.
    dateOfBirth: date("date_of_birth", { mode: "string" }),

    personalPhone1: text("personal_phone_1"),
    personalPhone2: text("personal_phone_2"),
    workPhone: text("work_phone"),
    personalEmail1: text("personal_email_1"),
    personalEmail2: text("personal_email_2"),
    workEmail: text("work_email"),

    // Added in Slice 14.15.01 — fields read off a Romanian ID card that have
    // no existing home, plus a citizenship FK. All nullable; populated either
    // manually or via the Import/Classify "Person" flow's vision extraction.
    placeOfBirth: text("place_of_birth"),
    idIssuingAuthority: text("id_issuing_authority"),
    idValidFrom: date("id_valid_from", { mode: "string" }),
    idValidUntil: date("id_valid_until", { mode: "string" }),
    idCardNumber: text("id_card_number"),
    idMrzRaw: text("id_mrz_raw"),
    citizenshipId: uuid("citizenship_id").references(() => lookupCitizenship.id, { onDelete: "set null" }),
  },
  (t) => [
    // At least one of first_name / last_name must be set.
    check(
      "natural_person_has_name",
      sql`${t.firstName} IS NOT NULL OR ${t.lastName} IS NOT NULL`,
    ),
    // NOTE: CNP uniqueness is NOT enforced here as a plain unique index.
    // A plain partial unique index can't see person.deleted_at (soft-delete
    // lives on the parent `person` row, not this table), so it would
    // permanently block reusing a CNP after its person was soft-deleted.
    // Enforced instead by a BEFORE INSERT OR UPDATE trigger
    // (natural_person_check_cnp_unique, migration_025) that only counts
    // collisions against non-soft-deleted persons.
  ],
);

// ---------------------------------------------------------------------------
// judicial_person — subtype for organisations / legal entities
// ---------------------------------------------------------------------------
//
// 1:1 with `person`. PK is also FK to person.id with ON DELETE CASCADE so
// hard-deleting a person also removes the satellite row. Soft delete (the
// API path) just sets person.deleted_at and leaves this row untouched.
//
// `notes` lives on the parent `person` row (same as natural_person).
// HEADQUARTERS + CORRESPONDENCE addresses are stored in the existing
// `address` table; both kinds already exist in addressKindEnum.

export const judicialPerson = pgTable(
  "judicial_person",
  {
    personId: uuid("person_id")
      .primaryKey()
      .references(() => person.id, { onDelete: "cascade" }),

    // Display / legal name. Required.
    name: text("name").notNull(),
    nickname: text("nickname"),

    // Judicial-person legal/organisational form (SRL/SA/PFA/etc.). Was a
    // fixed Postgres enum until Slice #15.07 — now an FK to the admin-managed
    // lookup_judicial_person_type table (Administration -> Reference Data ->
    // "Judicial Person Types"). Nullable; ON DELETE SET NULL so removing a
    // type from Reference Data just clears the tag rather than blocking the
    // delete or cascading.
    judicialPersonTypeId: uuid("judicial_person_type_id")
      .references(() => lookupJudicialPersonType.id, { onDelete: "set null" }),

    // CUI — Cod Unic de Inregistrare (Romanian fiscal registration code).
    // Optional. UNIQUE when present, but only among non-soft-deleted persons
    // — enforced by a trigger (migration_025), not a plain unique index (see
    // the matching note on natural_person.cnp above for why). Once set,
    // cannot be changed — enforced by a separate trigger (NULL -> value is
    // allowed; value -> anything-different is not).
    cuiNumber: text("cui_number"),

    // Trade Register number — "Nr. ORC" (e.g. "J22/123/2020").
    tradeRegisterNumber: text("trade_register_number"),

    // Contact persons — FK references to natural_person rows.
    // Nullable; ON DELETE SET NULL so removing the linked person just clears
    // the reference without touching this judicial_person row.
    contactPerson1Id: uuid("contact_person_1_id")
      .references(() => person.id, { onDelete: "set null" }),
    contactPerson2Id: uuid("contact_person_2_id")
      .references(() => person.id, { onDelete: "set null" }),

    // When true, the correspondence address mirrors the registered-office
    // address and no CORRESPONDENCE address row is stored in `address`.
    correspondenceSameAsHq: boolean("correspondence_same_as_hq")
      .notNull()
      .default(false),
  },
  (t) => [
    // NOTE: CUI uniqueness is enforced by a trigger
    // (judicial_person_check_cui_unique, migration_025), not a plain unique
    // index — see the matching note on natural_person.cnp for why.
  ],
);

// ---------------------------------------------------------------------------
// address — owned by a person, one row per (person, kind)
// ---------------------------------------------------------------------------
//
// FK cascades on hard-delete of person. When a user clears an address block
// in the form, we hard-delete the row directly (no deleted_at on address —
// addresses are part of the person's aggregate, not separately archived).

export const address = pgTable(
  "address",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    personId: uuid("person_id")
      .notNull()
      .references(() => person.id, { onDelete: "cascade" }),

    kind: addressKindEnum("kind").notNull(),

    // "Street, No., Block, Floor, Apt" — single free-form field per spec.
    streetLine: text("street_line"),
    postalCode: text("postal_code"),
    // "City, Locality, UAT, Commune, Village" — single free-form field.
    locality: text("locality"),
    // "County / Sector" — free text for now; will become FK later.
    county: text("county"),
    country: text("country").notNull(),
    notes: text("notes"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // A person can have at most one address of each kind.
    uniqueIndex("address_person_kind_unique").on(t.personId, t.kind),
  ],
);

// ---------------------------------------------------------------------------
// person_version — full-snapshot version history  (Slice #18.05)
// ---------------------------------------------------------------------------
//
// One row per saved version of a person (natural OR judicial — a single shared
// table, since both FK person.id). version_number is 0-based: version 0 is the
// state at creation, every saved edit appends the next number. Each row stores
// a COMPLETE snapshot (the person's own editable fields + its address blocks)
// as JSONB — reconstructing "version N" is a direct lookup, no delta replay.
//
// The label colour and per-field highlights shown in the UI are derived at
// display time by diffing snapshot N against snapshot N-1; nothing derived is
// persisted here. The snapshot JSON shape differs by person.type and lives next
// to the write paths in src/lib/persons/queries.ts (NaturalPersonSnapshot) and
// src/lib/judicial-persons/queries.ts (JudicialPersonSnapshot); both match the
// backfill in migration_030_person_versions.sql exactly.

export const personVersion = pgTable(
  "person_version",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    personId: uuid("person_id")
      .notNull()
      .references(() => person.id, { onDelete: "cascade" }),

    // 0-based; unique per person.
    versionNumber: integer("version_number").notNull(),

    // Full snapshot of the person at this version (own fields + addresses).
    // Untyped here to avoid a circular import; the query layer casts it to the
    // subtype's snapshot type.
    snapshot: jsonb("snapshot").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("person_version_person_number_unique").on(
      t.personId,
      t.versionNumber,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Enums — Property domain
// ---------------------------------------------------------------------------

// NOTE (Slice #15.16): the `property_type` and `use_category` Postgres enums
// were removed. Property type and use category are now admin-managed rows in
// Reference Data (lookup_property_type / lookup_use_category), referenced by
// nullable FK columns on `property` (propertyTypeId / useCategoryId).
// See migration_028_property_type_usecat_fk.sql.

// ---------------------------------------------------------------------------
// property — root entity
// ---------------------------------------------------------------------------
//
// Soft-delete via deleted_at (same pattern as person).
// Code is auto-generated from a Postgres sequence: PROP00001, PROP00002, ...
// The sequence is created in the migration (not expressible in Drizzle).

export const property = pgTable("property", {
  id: uuid("id").primaryKey().defaultRandom(),

  // FK to the shared principal_object row that owns this property's code.
  principalObjectId: uuid("principal_object_id")
    .notNull()
    .unique()
    .references(() => principalObject.id),

  // Human-readable code like "PROP00002". Copied from principal_object.code
  // at creation time. No DEFAULT — supplied by the app layer.
  code: text("code").notNull().unique(),

  // Property type — admin-managed (lookup_property_type, Reference Data ->
  // Property Types). Was a fixed `property_type` Postgres enum ("LAND") until
  // Slice #15.16. Nullable; ON DELETE SET NULL so removing a type from
  // Reference Data just clears the tag rather than blocking the delete.
  propertyTypeId: uuid("property_type_id")
    .references(() => lookupPropertyType.id, { onDelete: "set null" }),

  // "Porecla / elemente definitorii" — short identifying label.
  nickname: text("nickname"),

  // Romanian cadastral identifiers.
  tarlaSola:       text("tarla_sola"),       // Nr. tarla / sola
  parcela:         text("parcela"),           // Nr. parcela
  cadastralNumber: text("cadastral_number"),  // Nr. cadastru
  carteFunciara:   text("carte_funciara"),    // Nr. carte funciara

  // Use category — admin-managed (lookup_use_category, Reference Data -> Use
  // Categories). Was a fixed `use_category` Postgres enum (CATEG1/2/3) until
  // Slice #15.16. Nullable; ON DELETE SET NULL.
  useCategoryId: uuid("use_category_id")
    .references(() => lookupUseCategory.id, { onDelete: "set null" }),

  // "Suprafata in mp" — official/declared area in square metres (user-entered).
  surfaceAreaMp: numeric("surface_area_mp", { precision: 12, scale: 2 }),

  // Slice #18.09: system-computed area (m²) of the polygon formed by the
  // ordered corners. NOT user-editable — recomputed on every save from the
  // corners (WGS84 → Stereo 70 → shoelace). NULL when fewer than 3 corners.
  calculatedAreaMp: numeric("calculated_area_mp", { precision: 12, scale: 2 }),

  notes: text("notes"),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// property_address — single address block per property
// ---------------------------------------------------------------------------
//
// FK cascades on hard-delete of property. No `kind` column — a property has
// exactly one address. No deleted_at — clearing the address hard-deletes the
// row (same pattern as Person address).

export const propertyAddress = pgTable(
  "property_address",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    streetLine: text("street_line"),
    postalCode: text("postal_code"),
    locality:   text("locality"),
    county:     text("county"),
    country:    text("country").notNull(),
    notes:      text("notes"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // Each property has at most one address row.
    uniqueIndex("property_address_property_unique").on(t.propertyId),
  ],
);

// ---------------------------------------------------------------------------
// property_corner — ordered polygon vertices, stored as WGS84 decimal degrees
// ---------------------------------------------------------------------------
//
// Corners are the authoritative geometry. The polygon for map display is
// derived from the ordered corner set at query time. Heights are omitted —
// we store 2-D planimetric coordinates only.

export const propertyCorner = pgTable(
  "property_corner",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    // 1-based display order; unique per property.
    sequenceNo: integer("sequence_no").notNull(),

    // WGS84 / ETRS89 decimal degrees.
    lat: doublePrecision("lat").notNull(),
    lon: doublePrecision("lon").notNull(),

    // Original index token (column 1) from the imported cadastral text/OCR
    // source, kept permanently bound to this corner's lat/lon so it travels
    // with the corner when the table is reordered (e.g. fixing a bow-tie
    // polygon via the up/down arrows). Null when there was no source index
    // (manual entry, OCR groups, or the legacy 2-column text format).
    originalIndex: integer("original_index"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("property_corner_property_seq_unique").on(
      t.propertyId,
      t.sequenceNo,
    ),
  ],
);

// ---------------------------------------------------------------------------
// property_version — full-snapshot version history  (Slice #18.02)
// ---------------------------------------------------------------------------
//
// One row per saved version of a property. version_number is 0-based: version
// 0 is the state at creation, every saved edit appends the next number. Each
// row stores a COMPLETE snapshot (property fields + address + ordered corners)
// as JSONB — reconstructing "version N" is a direct lookup, no delta replay.
//
// The label colour and per-field highlights shown in the UI are derived at
// display time by diffing snapshot N against snapshot N-1; nothing derived is
// persisted here. Snapshot JSON shape lives next to the write path in
// src/lib/properties/queries.ts (PropertySnapshot) and matches the backfill in
// migration_029_property_versions.sql exactly.

export const propertyVersion = pgTable(
  "property_version",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    // 0-based; unique per property.
    versionNumber: integer("version_number").notNull(),

    // Full snapshot of the property at this version (property + address +
    // corners). Untyped here to avoid a circular import; the query layer casts
    // it to PropertySnapshot.
    snapshot: jsonb("snapshot").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("property_version_property_number_unique").on(
      t.propertyId,
      t.versionNumber,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Lookup / Reference-Data tables  (Slice #3 — Liste de Valori)
// ---------------------------------------------------------------------------
//
// These tables back the admin "Value Lists" screen. As of Slice #15.16 the
// property domain references lookup_property_type / lookup_use_category
// directly via FK columns on `property` (the old property_type / use_category
// pg enums were removed). Other enum→FK migrations may follow as the domain
// model settles.
//
// All tables share the same shape: uuid PK, payload fields, sort_order,
// created_at / updated_at (touched by the touch_updated_at trigger).

// ── Proprietate group ───────────────────────────────────────────────────────

export const lookupPropertyType = pgTable("lookup_property_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupTarla = pgTable("lookup_tarla", {
  id:        uuid("id").primaryKey().defaultRandom(),
  indicativ: text("indicativ").notNull(),
  descriere: text("descriere"),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupUseCategory = pgTable("lookup_use_category", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── Persoană group ──────────────────────────────────────────────────────────

export const lookupPersonType = pgTable("lookup_person_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupPersonRole = pgTable("lookup_person_role", {
  id:          uuid("id").primaryKey().defaultRandom(),
  name:        text("name").notNull(),
  description: text("description"),
  sortOrder:   integer("sort_order").notNull().default(0),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// Judicial-person legal/organisational form (SRL/SA/PFA/etc.). Replaces the
// fixed judicial_type Postgres enum as of Slice #15.07 — managed via
// Administration -> Reference Data -> "Judicial Person Types".
export const lookupJudicialPersonType = pgTable("lookup_judicial_person_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupCitizenship = pgTable("lookup_citizenship", {
  id:        uuid("id").primaryKey().defaultRandom(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── Document group ──────────────────────────────────────────────────────────

// `key` (Slice #15.05) is an immutable slug — e.g. "CONTRACT_VANZARE" — that
// application code switches on (per-type field visibility/labels in
// src/lib/documents/type-config.ts). `name` is the freely-editable Romanian
// display label shown in Reference Data; renaming `name` never breaks
// type-specific logic because code never matches on it. `key` is set once at
// row creation and should not be changed afterwards (no UI to edit it).
export const lookupDocumentType = pgTable("lookup_document_type", {
  id:        uuid("id").primaryKey().defaultRandom(),
  key:       text("key").notNull().unique(),
  name:      text("name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const lookupInstitution = pgTable("lookup_institution", {
  id:              uuid("id").primaryKey().defaultRandom(),
  name:            text("name").notNull(),
  institutionType: text("institution_type"),
  sortOrder:       integer("sort_order").notNull().default(0),
  createdAt:       timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:       timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── Property ↔ Person Role whitelist ────────────────────────────────────────
//
// Managed via the "Property Persons" admin panel.  Each row marks a role from
// lookup_person_role as a valid role tag for Property ↔ Person associations.
// ON DELETE CASCADE keeps this table clean when a role is removed.

export const lookupPropertyPersonRole = pgTable(
  "lookup_property_person_role",
  {
    id:           uuid("id").primaryKey().defaultRandom(),
    personRoleId: uuid("person_role_id")
      .notNull()
      .unique()
      .references(() => lookupPersonRole.id, { onDelete: "cascade" }),
    createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
);

// ── Document Type ↔ Person Role junction ────────────────────────────────────
//
// Managed via the "Document Persons" admin panel. Both FKs cascade on delete
// so removing a document type or person role automatically cleans up associations.

export const lookupDocTypePersonRole = pgTable(
  "lookup_doc_type_person_role",
  {
    id:             uuid("id").primaryKey().defaultRandom(),
    documentTypeId: uuid("document_type_id")
      .notNull()
      .references(() => lookupDocumentType.id, { onDelete: "cascade" }),
    personRoleId:   uuid("person_role_id")
      .notNull()
      .references(() => lookupPersonRole.id, { onDelete: "cascade" }),
    createdAt:      timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("lookup_doc_type_person_role_unique").on(t.documentTypeId, t.personRoleId),
  ],
);

// ── Others (was lookup_service_interest, renamed in migration 011) ──────────
//
// General-purpose bucket for categorised lookup values that don't belong to
// Property / Person / Document. Current categories: Serviciu, Interes, Grup,
// Stampila. The `category` column is injected by the query layer; the UI only
// exposes the `name` field.

export const lookupOthers = pgTable("lookup_others", {
  id:          uuid("id").primaryKey().defaultRandom(),
  name:        text("name").notNull(),
  description: text("description"),
  category:    text("category"),
  sortOrder:   integer("sort_order").notNull().default(0),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// document — root entity
// ---------------------------------------------------------------------------
//
// Single-table design: all document types share this table.
//
// NOTE (Slice #15.05): `type` was previously a fixed Postgres enum
// (`paperwork_type`, 21 hardcoded values). It is now a FK to
// `lookup_document_type` — document types are admin-managed rows in
// Reference Data (Administration → Reference Data → Document Types), never
// hardcoded in application code. Per standing rule: new type values are
// added as rows by Adrian, or by Claude only when explicitly directed —
// never auto-seeded by code or migrations going forward. No `onDelete`
// clause is set on purpose — Postgres' default "no action" blocks deleting
// a lookup_document_type row while any document still references it.
//
// Type-specific columns are nullable; the UI shows/hides them based on the
// resolved `lookup_document_type.key` (see src/lib/documents/type-config.ts).
//
// Columns marked "→ Slice 5" are temporary free-text placeholders that will
// be replaced by junction table relationships to Person in Slice 5.
//
// Code is auto-generated: DOC00001, DOC00002, …
// Soft-delete via deleted_at (same pattern as person / property).

export const document = pgTable("document", {
  id: uuid("id").primaryKey().defaultRandom(),

  // FK to the shared principal_object row that owns this document's code.
  principalObjectId: uuid("principal_object_id")
    .notNull()
    .unique()
    .references(() => principalObject.id),

  // Human-readable code like "DOC00005". Copied from principal_object.code
  // at creation time. No DEFAULT — supplied by the app layer.
  code: text("code").notNull().unique(),

  // FK to lookup_document_type — see note above. Deliberately no onDelete:
  // Postgres' default behaviour (RESTRICT) blocks deleting a type that is
  // still in use, which is exactly the protection we want.
  documentTypeId: uuid("document_type_id")
    .notNull()
    .references(() => lookupDocumentType.id),

  // Short identifying label — the "Porecla" equivalent for a document.
  // e.g. "Vânzare Popescu 2021", "Titlu Teren Nord"
  title: text("title"),

  // ── Common fields (UI label varies by type) ────────────────────────────
  // "Nr. titlu / nr. certificat / nr. contract / nr. hotărâre / …"
  nrDocument:   text("nr_document"),
  // "Data autentificarii" / "Data eliberarii" / "Data emiterii"
  dateDocument: date("date_document", { mode: "string" }),
  // "Notariat" / "Institutie unde este inregistrat" / "Emitent" (generic)
  institution:  text("institution"),

  // ── Titlu de Proprietate specific ──────────────────────────────────────
  emitent:       text("emitent"),
  bazaLegala:    text("baza_legala"),
  uatProprietate: text("uat_proprietate"),
  uatProprietar:  text("uat_proprietar"),
  // Suprafata — numeric, same precision as property.surface_area_mp
  suprafata:     numeric("suprafata", { precision: 12, scale: 2 }),

  // ── Certificat de Moștenitor specific ─────────────────────────────────
  nrDosarSuccesoral: text("nr_dosar_succesoral"),
  dataDecesului:     date("data_decesului", { mode: "string" }),
  ultimulDomiciliu:  text("ultimul_domiciliu"),
  nrCertificatDeces: text("nr_certificat_deces"),

  // ── Contract de Închiriere specific ───────────────────────────────────
  dateStart: date("date_start", { mode: "string" }), // Data incepere contract
  dateEnd:   date("date_end",   { mode: "string" }), // Data incheierii valabilitate

  // ── Party placeholders (→ Slice 5 Person relationships) ───────────────
  // titularText : Titlu proprietate — Titular
  titularText:   text("titular_text"),
  // defunctText : Titlu proprietate / Certificat mostenitor — Defunct
  //               Testament — Testator
  defunctText:   text("defunct_text"),
  // partiesAText: Vanzatori / Proprietari / Donatori
  partiesAText:  text("parties_a_text"),
  // partiesBText: Cumparatori / Chiriasi / Donatari / Mostenitori
  partiesBText:  text("parties_b_text"),

  // ── Always present ─────────────────────────────────────────────────────
  notes: text("notes"), // Observatii

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// document_version — full-snapshot version history  (Slice #18.06)
// ---------------------------------------------------------------------------
//
// One row per saved version of a document. version_number is 0-based: version
// 0 is the state at creation, every saved edit appends the next number. Each
// row stores a COMPLETE snapshot (the document's own editable fields) as JSONB
// — reconstructing "version N" is a direct lookup, no delta replay. The
// versioned scope is the document's form fields only (NOT the M:M associations
// nor the uploaded document_page files).
//
// The label colour and per-field highlights shown in the UI are derived at
// display time by diffing snapshot N against snapshot N-1; nothing derived is
// persisted here. The snapshot JSON shape lives next to the write path in
// src/lib/documents/queries.ts (DocumentSnapshot) and matches the backfill in
// migration_031_document_versions.sql exactly.

export const documentVersion = pgTable(
  "document_version",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    documentId: uuid("document_id")
      .notNull()
      .references(() => document.id, { onDelete: "cascade" }),

    // 0-based; unique per document.
    versionNumber: integer("version_number").notNull(),

    // Full snapshot of the document at this version. Untyped here to avoid a
    // circular import; the query layer casts it to DocumentSnapshot.
    snapshot: jsonb("snapshot").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("document_version_document_number_unique").on(
      t.documentId,
      t.versionNumber,
    ),
  ],
);

// ---------------------------------------------------------------------------
// property_person — M:M junction between Property and Person  (Slice #5.1)
// ---------------------------------------------------------------------------
//
// No deleted_at — associations are hard-deleted (same pattern as address rows).
// ON DELETE CASCADE on both sides keeps this table clean automatically.
// Duplicate associations are blocked by the unique index.

export const propertyPerson = pgTable(
  "property_person",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    propertyId: uuid("property_id")
      .notNull()
      .references(() => property.id, { onDelete: "cascade" }),

    personId: uuid("person_id")
      .notNull()
      .references(() => person.id, { onDelete: "cascade" }),

    // Optional role tag from the Property Persons whitelist.
    // ON DELETE SET NULL — cleared automatically if the role is removed.
    personRoleId: uuid("person_role_id")
      .references(() => lookupPersonRole.id, { onDelete: "set null" }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("property_person_unique").on(t.propertyId, t.personId),
  ],
);

// ---------------------------------------------------------------------------
// M:M junction tables  (Slice #5.1 + #5.2)
// ---------------------------------------------------------------------------

// property <-> document  (Slice 5.2)
export const propertyDocument = pgTable(
  "property_document",
  {
    id:         uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").notNull().references(() => property.id, { onDelete: "cascade" }),
    documentId: uuid("document_id").notNull().references(() => document.id, { onDelete: "cascade" }),
    createdAt:  timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("property_document_unique").on(t.propertyId, t.documentId)],
);

// property <-> property  (self-ref, symmetric; id_a < id_b enforced by CHECK)
export const propertyProperty = pgTable(
  "property_property",
  {
    id:           uuid("id").primaryKey().defaultRandom(),
    propertyIdA:  uuid("property_id_a").notNull().references(() => property.id, { onDelete: "cascade" }),
    propertyIdB:  uuid("property_id_b").notNull().references(() => property.id, { onDelete: "cascade" }),
    createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("property_property_unique").on(t.propertyIdA, t.propertyIdB),
    check("property_property_order", sql`${t.propertyIdA} < ${t.propertyIdB}`),
  ],
);

// person <-> document  (Slice 5.2)
export const personDocument = pgTable(
  "person_document",
  {
    id:         uuid("id").primaryKey().defaultRandom(),
    personId:   uuid("person_id").notNull().references(() => person.id,   { onDelete: "cascade" }),
    documentId: uuid("document_id").notNull().references(() => document.id, { onDelete: "cascade" }),
    // Optional role tag — used by Certificat de Moștenitor.
    // 'DEFUNCT' = the deceased person; 'MOSTENITOR' = an inheritor.
    // NULL for persons linked via the general Persons tab on any doc type.
    quality:    text("quality"),
    // Optional person role from the Document Persons whitelist (lookup_doc_type_person_role).
    // ON DELETE SET NULL — cleared automatically if the role is removed from lookup_person_role.
    personRoleId: uuid("person_role_id")
      .references(() => lookupPersonRole.id, { onDelete: "set null" }),
    createdAt:  timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("person_document_unique").on(t.personId, t.documentId)],
);


// person <-> person  (self-ref, symmetric; id_a < id_b enforced by CHECK)
export const personPerson = pgTable(
  "person_person",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    personIdA:   uuid("person_id_a").notNull().references(() => person.id, { onDelete: "cascade" }),
    personIdB:   uuid("person_id_b").notNull().references(() => person.id, { onDelete: "cascade" }),
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("person_person_unique").on(t.personIdA, t.personIdB),
    check("person_person_order", sql`${t.personIdA} < ${t.personIdB}`),
  ],
);

// ---------------------------------------------------------------------------
// document_page — uploaded file pages attached to a document record
// ---------------------------------------------------------------------------
//
// One row per uploaded file. File is stored either on the local filesystem
// (development) or in Supabase Storage bucket "document-pages" (production,
// renamed from "paperwork-pages" in Slice #15.05). `file_path` is the
// storage key in both cases.

export const documentPage = pgTable(
  "document_page",
  {
    id:         uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => document.id, { onDelete: "cascade" }),
    pageNumber: integer("page_number").notNull(),
    pageName:   text("page_name"),
    pageNotes:  text("page_notes"),
    // Original filename as uploaded by the user, e.g. "scan001.pdf"
    fileName:   text("file_name").notNull(),
    // Storage path/key, e.g. "document-pages/{documentId}/{pageId}.pdf"
    filePath:   text("file_path").notNull(),
    fileSize:   integer("file_size"),     // bytes
    mimeType:   text("mime_type"),
    createdAt:  timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt:  timestamp("updated_at",  { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("document_page_document_number_unique").on(
      t.documentId,
      t.pageNumber,
    ),
  ],
);

// document <-> document  (self-ref, symmetric; id_a < id_b enforced by CHECK)
export const documentDocument = pgTable(
  "document_document",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    documentIdA: uuid("document_id_a").notNull().references(() => document.id, { onDelete: "cascade" }),
    documentIdB: uuid("document_id_b").notNull().references(() => document.id, { onDelete: "cascade" }),
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("document_document_unique").on(t.documentIdA, t.documentIdB),
    check("document_document_order", sql`${t.documentIdA} < ${t.documentIdB}`),
  ],
);

// ---------------------------------------------------------------------------
// groups + group_member — Groups feature  (Slice #18.07)
// ---------------------------------------------------------------------------
//
// A Group gathers items of a single target type. The two-letter `code`
// (AA, AB, ... skipping I/O) is allocated from `group_code_seq` (created in
// migration_032) and encoded in the query layer (src/lib/groups/code.ts);
// codes are never reused. `description` is required. `lastPosition` is a
// high-water counter: member positions are allocated from it and never reused
// (removing a member leaves a gap). Only PROPERTY membership is wired for now.

export const groupTargetTypeEnum = pgEnum("group_target_type", [
  "PHYSICAL_PERSON",
  "JUDICIAL_PERSON",
  "PROPERTY",
  "DOCUMENT",
]);

export const groups = pgTable("groups", {
  id:          uuid("id").primaryKey().defaultRandom(),
  // Two-letter system code (AA, AB, …). Allocated + encoded by the app layer.
  code:        text("code").notNull().unique(),
  targetType:  groupTargetTypeEnum("target_type").notNull(),
  description: text("description").notNull(),
  // High-water counter for member positions; never decreases (no reuse).
  lastPosition: integer("last_position").notNull().default(0),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const groupMember = pgTable(
  "group_member",
  {
    id:      uuid("id").primaryKey().defaultRandom(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    // Only PROPERTY target is wired for now; nullable so the table can grow
    // other typed member FKs later without a destructive migration.
    propertyId: uuid("property_id")
      .references(() => property.id, { onDelete: "cascade" }),
    // 1-based position within the group; unique per group; never reused.
    position: integer("position").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("group_member_group_position_unique").on(t.groupId, t.position),
    uniqueIndex("group_member_group_property_unique").on(t.groupId, t.propertyId),
  ],
);

// ---------------------------------------------------------------------------
// Auth — user_requests + app_users  (Slice #7.0)
// ---------------------------------------------------------------------------
//
// user_requests: staging table for sign-up applications.
//   status: pending → approved | rejected
//   No FK to app_users — admin reads and acts on requests independently.
//
// app_users: links a Supabase Auth UID to an app-level username + role.
//   supabase_uid is unique (one app record per auth identity).
//   username is unique.
//   role: "superuser" | "user"
//   approved_by: username of the admin who approved this account (null for
//   the seeded superuser).

export const userRequestStatusEnum = pgEnum("user_request_status", [
  "pending",
  "approved",
  "rejected",
]);

export const appUserRoleEnum = pgEnum("app_user_role", [
  "superuser",
  "user",
]);

export const userRequests = pgTable(
  "user_requests",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    email:       text("email").notNull(),
    username:    text("username").notNull(),
    status:      userRequestStatusEnum("status").notNull().default("pending"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    processedBy: text("processed_by"),   // username of the admin who acted
    // Store whether a welcome email was sent successfully
    emailSent:   boolean("email_sent").notNull().default(false),
  },
  (t) => [
    uniqueIndex("user_requests_email_pending_unique")
      .on(t.email)
      .where(sql`${t.status} = 'pending'`),
  ],
);

export const appUsers = pgTable(
  "app_users",
  {
    id:          uuid("id").primaryKey().defaultRandom(),
    // Supabase Auth user UUID — set when account is created via Admin API.
    // Null only for a brief window between request approval and account creation
    // (handled atomically, so in practice always set).
    supabaseUid: text("supabase_uid").unique(),
    email:       text("email").notNull().unique(),
    username:    text("username").notNull().unique(),
    role:        appUserRoleEnum("role").notNull().default("user"),
    approvedBy:  text("approved_by"),   // null for the seeded superuser
    createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
);

// ---------------------------------------------------------------------------
// Help — help_content + help_hint  (Slice #16.UX.02)
// ---------------------------------------------------------------------------
//
// On-screen help, self-served by Adrian via Administration -> Help Content.
// Two content types:
//   1. help_content — one row per "screen" (Background + How-To, bilingual),
//      surfaced via the <HelpButton> popover.
//   2. help_hint — micro-hints for hidden mouse/keyboard behaviour (e.g. drag
//      to select on the Properties Map, wheel-zoom on the Document big-page
//      viewer), surfaced via the lighter <HelpHint> inline component.
//
// `screenKey` / `hintKey` values are NOT free text — they must match an entry
// in the code-side registry (src/lib/help/registry.ts), which is the single
// source of truth for which screens/hints exist. The DB rows only ever
// *supply content* for a registry entry; a registry entry with no DB row
// simply renders nothing (no Help button / no hint shown).

export const helpContent = pgTable("help_content", {
  id:           uuid("id").primaryKey().defaultRandom(),
  screenKey:    text("screen_key").notNull().unique(),
  backgroundEn: text("background_en"),
  backgroundRo: text("background_ro"),
  howToEn:      text("how_to_en"),
  howToRo:      text("how_to_ro"),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:    timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const helpHint = pgTable(
  "help_hint",
  {
    id:        uuid("id").primaryKey().defaultRandom(),
    screenKey: text("screen_key").notNull(),
    hintKey:   text("hint_key").notNull(),
    textEn:    text("text_en"),
    textRo:    text("text_ro"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("help_hint_screen_hint_unique").on(t.screenKey, t.hintKey),
  ],
);
