-- migration_062_calculation_runs.sql  (Slice #20.09)
--
-- Adds calculation provenance tracking:
--   calculation_run        — one row per committed algorithm run
--   calculation_run_output — junction: run → principal_object (created by the run)
--
-- Safe to re-run (all DDL uses IF NOT EXISTS / DO blocks).

-- ---------------------------------------------------------------------------
-- 1. Record this migration
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations (filename)
VALUES ('migration_062_calculation_runs.sql')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Sequence for CALC codes (CALC00001, CALC00002, ...)
-- ---------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS calculation_run_code_seq
  START WITH 1
  INCREMENT BY 1
  NO CYCLE;

-- ---------------------------------------------------------------------------
-- 3. calculation_run
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS calculation_run (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable code, e.g. "CALC00001". Generated by the app layer using
  -- the sequence above; never reused.
  code             text        NOT NULL UNIQUE,

  -- Short algorithm identifier — extensible without migrations.
  -- Current value: 'PARCEL_DIVISION'
  algorithm_type   text        NOT NULL,

  -- Full input that was submitted to the algorithm (file text, options, etc.)
  -- Stored as JSONB so the form can be pre-filled for a re-run.
  input_params     jsonb       NOT NULL,

  -- Structured output from the computation (orientation, owners, areas, road,
  -- border coordinates in both Stereo 70 and WGS84). Used to render the
  -- read-only steps table and the map preview in the history detail page.
  steps_log        jsonb       NOT NULL DEFAULT '{}',

  -- FK to the Group that was created together with this run's output objects.
  -- Nullable: future algorithm types might not produce a group.
  result_group_id  uuid        REFERENCES groups(id) ON DELETE SET NULL,

  -- 'active'     — the run's outputs are the current authoritative objects.
  -- 'superseded' — a later run replaced these outputs (Phase C).
  status           text        NOT NULL DEFAULT 'active'
                               CHECK (status IN ('active', 'superseded')),

  notes            text,

  -- Email of the user who triggered the run (from Supabase session).
  created_by       text,

  created_at       timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 4. calculation_run_output
-- ---------------------------------------------------------------------------
-- One row per principal_object created by a run. Allows future algorithm types
-- to produce any mix of Properties, Persons, or Documents.
CREATE TABLE IF NOT EXISTS calculation_run_output (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  calculation_run_id    uuid NOT NULL
                             REFERENCES calculation_run(id) ON DELETE CASCADE,

  -- Points to whichever principal_object was created (Property, Person, or
  -- Document). Cascades so removing the entity cleans up this row.
  principal_object_id   uuid NOT NULL
                             REFERENCES principal_object(id) ON DELETE CASCADE,

  -- Role of this output within the run (e.g. 'OWNER_PARCEL', 'ROAD_PARCEL').
  -- Extensible free text.
  output_role           text NOT NULL DEFAULT 'OWNER_PARCEL',

  created_at            timestamptz NOT NULL DEFAULT now(),

  UNIQUE (calculation_run_id, principal_object_id)
);

CREATE INDEX IF NOT EXISTS calculation_run_output_run_idx
  ON calculation_run_output (calculation_run_id);

CREATE INDEX IF NOT EXISTS calculation_run_output_po_idx
  ON calculation_run_output (principal_object_id);
