-- migration_085_seed_cvc_templates.sql
--
-- Slice #36.01 — the „Contract de Vânzare" and „Act Adițional" forms.
--
-- WHAT THIS DOES
-- --------------
-- Writes `template_fields` onto two rows of `lookup_document_type`. That is
-- all. It is a DATA migration: no column is added, no constraint is created,
-- nothing is dropped, and it can be re-run — the two UPDATEs are unconditional
-- writes of a literal, not merges.
--
-- WHY IT IS A MIGRATION AND NOT A FORM-EDITOR SESSION
-- ---------------------------------------------------
-- The template mechanism is deliberately data — „adding a new document type's
-- full template is a DB row, never a schema migration or a code deploy"
-- (migration_066, and template-fields.ts's header). That is a statement about
-- the SCHEMA, not a licence to leave a form in one database. A template typed
-- into Reference Data exists only there: `Verify-Rebuild.ps1` replays the
-- migration chain and `src/db/sync-reference-data.sql` seeds the reference
-- rows, and neither would know about it. So these two forms ship twice — here,
-- for a database that is migrated forward, and in `sync-reference-data.sql`,
-- for one that is rebuilt from scratch — and `src/__tests__/cvc-template.test.ts`
-- asserts the two copies are identical.
--
-- WHAT IS DELIBERATELY *NOT* A FIELD IN EITHER FORM
-- -------------------------------------------------
-- Four repeating groups that a notarial deed is mostly made of, because
-- `document.custom_fields` is `Record<string, string | null>` — one string per
-- key, flat — and there is no `useFieldArray` anywhere in `src/`. Expressed as
-- template fields they would need the `_2` / `_3` suffixes that finding F5 of
-- the #29.01 import report already produced once:
--
--   * PARTIES -> `person_document`, one row per person per role, with the
--     cotă-parte on the row (migration_084). One deed carries three buyers at
--     63,64 / 9,09 / 27,27 percent; another carries one man who is both a
--     seller in his own name and the mandatar of three others.
--   * OBJECT OF SALE -> `property`, through `property_document`. A type-4 deed
--     — a lot plus 10,41% of an access road — is TWO linked properties.
--   * THE SELLER'S TITLE CHAIN -> `document_document`, with a
--     `lookup_document_document_role`. Every event in a chain is an instrument
--     the catalogue already knows. A 2016 deed with reconstituire ->
--     moștenire -> partaj -> CVC anterior is four links, not four field sets.
--   * SUPPORTING CERTIFICATES -> the same mechanism. CERTIFICAT_FISCAL,
--     EXTRAS_CARTE_FUNCIARA, CERTIFICAT_SARCINI, PROCURA, ANTECONTRACT and
--     CERTIFICAT_URBANISM are all seeded types, and the act adițional's parent
--     CVC is one more link of the same kind.
--
-- That is also the arithmetic that makes the form fit. Folded back in, „Contract
-- de Vânzare" needs well over a hundred fields; left as associations the scalar
-- remainder is 53, under the 60 `MAX_TEMPLATE_FIELDS` allows.
--
-- ⚠️ **AN INSTRUMENT THE DEED *CITES* BUT THE ARCHIVE DOES NOT HOLD STILL HAS
-- NOWHERE TO GO, AND THAT IS KNOWN.** „Titlu de proprietate nr. N/zz.ll.aaaa,
-- CJSDPT X" cannot be a link when no such document row exists, and this
-- migration deliberately mints no `titluNr` / `titluData` fields as a stop-gap,
-- because a four-event chain would immediately need `_2`, `_3` and `_4` — F5
-- again. Until `Slice.36.03` ships, such a citation lands in `unmappedRaw` and
-- is folded into „Note extinse" by the ai-interpret route. That is the symptom
-- Adrian named, it is not closed here, and 36.03 is the slice that closes it.
--
-- ONE FORM FOR FIVE FLAVOURS, AND A SECOND FOR THE SIXTH
-- ------------------------------------------------------
-- Groups 1 to 5 of the archive differ by THE STATE OF THE PAPERWORK — no
-- cadastral number yet, a temporary /N land book, a later completion, a
-- compound object — which is a fact about one transaction, not a class of
-- document. So they share one form and „Categorie internă" records which
-- flavour a deed is (filterable for free: `customFieldFilter` and
-- `GET /api/documents/custom-field-values`, #34.10). Only group 6, the act
-- adițional, is a different instrument, and it already has its own type row.
--
-- NOTHING IS DROPPED
-- ------------------
-- Both rows carry `template_fields` NULL today — this is greenfield, not a
-- rewrite — so there is no `custom_fields` value anywhere in the archive that
-- these writes could orphan. Verified before writing:
--   SELECT key, template_fields IS NOT NULL FROM lookup_document_type
--    WHERE key IN ('CONTRACT_VANZARE', 'ACT_ADITIONAL');

SET client_encoding = 'UTF8';

-- ── „Contract de Vânzare" — 53 fields over 4 notebook tabs ────────────
UPDATE lookup_document_type
   SET template_fields = $cvc$
[
  {"key": "pretTotal", "labelRo": "Preț total", "labelEn": "Total price", "type": "number", "order": 0, "aiHint": "suma, doar cifre și separator zecimal, fără moneda și fără punct de mie", "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "monedaPret", "labelRo": "Monedă", "labelEn": "Currency", "type": "select", "order": 1, "aiHint": null, "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": [{"value": "RON", "labelRo": "Lei (RON)", "labelEn": "Lei (RON)"}, {"value": "EUR", "labelRo": "Euro (EUR)", "labelEn": "Euro (EUR)"}, {"value": "USD", "labelRo": "Dolari (USD)", "labelEn": "Dollars (USD)"}]},
  {"key": "starePlata", "labelRo": "Stare plată", "labelEn": "Payment status", "type": "select", "order": 2, "aiHint": null, "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": [{"value": "ACHITAT_INTEGRAL", "labelRo": "Achitat integral", "labelEn": "Paid in full"}, {"value": "ACHITAT_ANTECONTRACT", "labelRo": "Achitat la antecontract", "labelEn": "Paid under the promise"}, {"value": "ACHITAT_PARTIAL", "labelRo": "Achitat parțial", "labelEn": "Partly paid"}, {"value": "DE_ACHITAT", "labelRo": "De achitat", "labelEn": "To be paid"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "modalitatePlata", "labelRo": "Modalitate plată", "labelEn": "Payment method", "type": "select", "order": 3, "aiHint": null, "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": [{"value": "NUMERAR", "labelRo": "Numerar", "labelEn": "Cash"}, {"value": "VIRAMENT", "labelRo": "Virament bancar", "labelEn": "Bank transfer"}, {"value": "MIXT", "labelRo": "Mixt", "labelEn": "Mixed"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "dataPlatii", "labelRo": "Data plății", "labelEn": "Payment date", "type": "date", "order": 4, "aiHint": "data la care prețul a fost încasat, când actul o dă separat de autentificare", "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "temeiPret", "labelRo": "Temei preț", "labelEn": "Price basis", "type": "text", "order": 5, "aiHint": "actul pe care se sprijină prețul, ca tip, număr și dată — «antecontract nr. N/zz.ll.aaaa», «promisiune bilaterală nr. N/zz.ll.aaaa»", "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "alocarePret", "labelRo": "Alocare preț", "labelEn": "Price allocation", "type": "text", "order": 6, "aiHint": "cum se împarte prețul, pe unități sau pe vânzători — «X lei lotul, Y lei cota de drum», «60% / 40%»", "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "scopVanzare", "labelRo": "Scop vânzare", "labelEn": "Purpose of sale", "type": "select", "order": 7, "aiHint": null, "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": [{"value": "OBISNUITA", "labelRo": "Vânzare obișnuită", "labelEn": "Ordinary sale"}, {"value": "COMASARE", "labelRo": "Comasare", "labelEn": "Merger with other plots"}, {"value": "ALTUL", "labelRo": "Alt scop", "labelEn": "Other purpose"}]},
  {"key": "predareStapanire", "labelRo": "Predare stăpânire", "labelEn": "Transfer of possession", "type": "select", "order": 8, "aiHint": null, "groupRo": "Financiar", "groupEn": "Financial", "tabRo": "Instrument", "tabEn": "Instrument", "options": [{"value": "LA_AUTENTIFICARE", "labelRo": "La autentificare", "labelEn": "On authentication"}, {"value": "ULTERIOR", "labelRo": "Ulterior", "labelEn": "Later"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "taxaTimbruPublicitate", "labelRo": "Taxă timbru și publicitate", "labelEn": "Stamp and land-publicity fee", "type": "number", "order": 9, "aiHint": "suma totală, doar cifre; când actul le dă separat, aici merge suma lor", "groupRo": "Taxe și onorarii", "groupEn": "Fees", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "timbruJudiciar", "labelRo": "Timbru judiciar", "labelEn": "Court stamp", "type": "number", "order": 10, "aiHint": "suma, doar cifre", "groupRo": "Taxe și onorarii", "groupEn": "Fees", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "onorariuNotarial", "labelRo": "Onorariu notarial", "labelEn": "Notary fee", "type": "number", "order": 11, "aiHint": "onorariul cu TVA inclus, doar cifre", "groupRo": "Taxe și onorarii", "groupEn": "Fees", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "impozitTransfer", "labelRo": "Impozit transfer", "labelEn": "Transfer tax", "type": "number", "order": 12, "aiHint": "impozitul pe transferul proprietății, doar cifre", "groupRo": "Taxe și onorarii", "groupEn": "Fees", "tabRo": "Instrument", "tabEn": "Instrument", "options": null},
  {"key": "categorieInterna", "labelRo": "Categorie internă", "labelEn": "Internal category", "type": "select", "order": 13, "aiHint": "starea dosarului, nu un alt tip de act", "groupRo": "Antet instrument", "groupEn": "Instrument header", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "1", "labelRo": "1 — Cadastru vechi, CF nedefinitivă", "labelEn": "1 — Old cadastre, temporary land book"}, {"value": "2", "labelRo": "2 — Fără cadastru, pentru comasare", "labelEn": "2 — No cadastre, for merger"}, {"value": "3", "labelRo": "3 — Fără cadastru, completat ulterior", "labelEn": "3 — No cadastre, later completed"}, {"value": "4", "labelRo": "4 — Lot plus cotă de drum", "labelEn": "4 — Lot plus road share"}, {"value": "5", "labelRo": "5 — Documentație completă", "labelEn": "5 — Complete documentation"}]},
  {"key": "documentatieFinalizata", "labelRo": "Documentație finalizată", "labelEn": "File complete", "type": "select", "order": 14, "aiHint": null, "groupRo": "Antet instrument", "groupEn": "Instrument header", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "DA", "labelRo": "Da", "labelEn": "Yes"}, {"value": "NU", "labelRo": "Nu", "labelEn": "No"}, {"value": "DA_DUPA_COMPLETARE", "labelRo": "Da, după completare", "labelEn": "Yes, after the supplement"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "calitateExemplar", "labelRo": "Calitate exemplar", "labelEn": "Copy status", "type": "select", "order": 15, "aiHint": null, "groupRo": "Antet instrument", "groupEn": "Instrument header", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "ORIGINAL", "labelRo": "Original", "labelEn": "Original"}, {"value": "DUPLICAT", "labelRo": "Duplicat", "labelEn": "Duplicate"}, {"value": "COPIE_LEGALIZATA", "labelRo": "Copie legalizată", "labelEn": "Certified copy"}]},
  {"key": "exemplareEmise", "labelRo": "Exemplare emise", "labelEn": "Originals issued", "type": "text", "order": 16, "aiHint": "numărul de exemplare și câte au rămas părților — «7, din care 5 părților»", "groupRo": "Antet instrument", "groupEn": "Instrument header", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "temeiAutentificare", "labelRo": "Temei autentificare", "labelEn": "Legal basis of authenticity", "type": "text", "order": 17, "aiHint": "articolul și legea invocate în încheierea de autentificare — «art. N lit. x Legea N/aaaa»", "groupRo": "Antet instrument", "groupEn": "Instrument header", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "dataContinut", "labelRo": "Data conținutului", "labelEn": "Content date", "type": "text", "order": 18, "aiHint": "anul sau data care se citește din corpul actului, când încheierea de autentificare lipsește de pe scan", "groupRo": "Antet instrument", "groupEn": "Instrument header", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "temeiExceptieCadastru", "labelRo": "Temei excepție cadastru", "labelEn": "Cadastre exemption basis", "type": "text", "order": 19, "aiHint": "temeiul pe care actul se încheie fără număr cadastral — «Titlul X art. N Legea N/aaaa»; gol când actul are cadastru", "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "marcajCarteFunciara", "labelRo": "Marcaj carte funciară", "labelEn": "Land-book marker", "type": "select", "order": 20, "aiHint": null, "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "DEFINITIVA", "labelRo": "Carte funciară definitivă", "labelEn": "Final land book"}, {"value": "NEDEFINITIVA", "labelRo": "Carte funciară nedefinitivă (/N)", "labelEn": "Temporary land book (/N)"}, {"value": "FARA_CF", "labelRo": "Fără carte funciară", "labelEn": "No land book"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "poateFiIntabulat", "labelRo": "Intabulare posibilă", "labelEn": "Can be tabulated now", "type": "select", "order": 21, "aiHint": null, "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "DA", "labelRo": "Da", "labelEn": "Yes"}, {"value": "NU", "labelRo": "Nu", "labelEn": "No"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "renuntareCercetareOcpi", "labelRo": "Renunțare cercetare OCPI", "labelEn": "Waiver of OCPI search", "type": "select", "order": 22, "aiHint": null, "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "obligatieNrCadastral", "labelRo": "Obligație număr cadastral", "labelEn": "Duty to obtain cadastral number", "type": "select", "order": 23, "aiHint": null, "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "VANZATOR", "labelRo": "Vânzător", "labelEn": "Seller"}, {"value": "CUMPARATOR", "labelRo": "Cumpărător", "labelEn": "Buyer"}, {"value": "AMBELE", "labelRo": "Ambele părți", "labelEn": "Both parties"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "termenFormalitati", "labelRo": "Termen formalități", "labelEn": "Deadline for formalities", "type": "text", "order": 24, "aiHint": "termenul dat pentru cadastru, intabulare sau rol fiscal — «N zile de la autentificare»", "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "completareUlterioara", "labelRo": "Completare ulterioară", "labelEn": "Later completion", "type": "text", "order": 25, "aiHint": "actul care completează acest contract, ca tip, număr și dată — «încheiere nr. N/zz.ll.aaaa»; gol când nu există", "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "consimtamantRadiere", "labelRo": "Consimțământ radiere", "labelEn": "Consent to radiation", "type": "select", "order": 26, "aiHint": null, "groupRo": "Excepție cadastru", "groupEn": "Cadastre exception", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "vecinatati", "labelRo": "Vecinătăți", "labelEn": "Neighbours", "type": "textarea", "order": 27, "aiHint": "vecinii pe laturi, cu lungimile când actul le dă, ca text — «N — ...; E — ...; S — ...; V — ...»", "groupRo": "Obiect declarat", "groupEn": "Declared object", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "origineLot", "labelRo": "Origine lot", "labelEn": "Origin of the lot", "type": "textarea", "order": 28, "aiHint": "actul din care a rezultat lotul — «lot rezultat din dezmembrarea actului nr. N/zz.ll.aaaa»", "groupRo": "Obiect declarat", "groupEn": "Declared object", "tabRo": "Cadastru", "tabEn": "Cadastre", "options": null},
  {"key": "inCircuitCivil", "labelRo": "Circuit civil", "labelEn": "In the civil circuit", "type": "select", "order": 29, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "liberDeSarcini", "labelRo": "Liber de sarcini", "labelEn": "Free of encumbrances", "type": "select", "order": 30, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "faraServituti", "labelRo": "Lipsă servituți", "labelEn": "Free of easements", "type": "select", "order": 31, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "neipotecat", "labelRo": "Neipotecat", "labelEn": "Not mortgaged", "type": "select", "order": 32, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "nepromisAltcuiva", "labelRo": "Nepromis altcuiva", "labelEn": "Not promised to another", "type": "select", "order": 33, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "nearendat", "labelRo": "Nearendat", "labelEn": "Not leased", "type": "select", "order": 34, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "neaportatSocietate", "labelRo": "Neaportat la capital", "labelEn": "Not contributed to share capital", "type": "select", "order": 35, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "faraLitigii", "labelRo": "Lipsă litigii", "labelEn": "No claims or restitution proceedings", "type": "select", "order": 36, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "faraExpropriere", "labelRo": "Lipsă expropriere", "labelEn": "Not under expropriation", "type": "select", "order": 37, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "faraMonumentIstoric", "labelRo": "Lipsă monument istoric", "labelEn": "Not a listed monument", "type": "select", "order": 38, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "nedezmembratContrar", "labelRo": "Nedezmembrat contrar extrasului", "labelEn": "Not subdivided contrary to the extract", "type": "select", "order": 39, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "garantieEvictiune", "labelRo": "Garanție evicțiune", "labelEn": "Eviction warranty", "type": "select", "order": 40, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "garantieVicii", "labelRo": "Garanție vicii ascunse", "labelEn": "Hidden-defect warranty", "type": "select", "order": 41, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "cumparatorCunoasteSituatia", "labelRo": "Situație cunoscută", "labelEn": "Buyer knows the situation", "type": "select", "order": 42, "aiHint": null, "groupRo": "Stare juridică afirmată", "groupEn": "Asserted legal situation", "tabRo": "Stare juridică", "tabEn": "Legal status", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "temeiLegalEvictiune", "labelRo": "Temei legal evicțiune", "labelEn": "Eviction warranty citation", "type": "text", "order": 43, "aiHint": "articolele citate pentru evicțiune și vicii — «art. N Cod civil», «art. N și N Cod civil»", "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": null},
  {"key": "declaratieArt292", "labelRo": "Declarație art. 292 CP", "labelEn": "Criminal-code non-alienation declaration", "type": "select", "order": 44, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "pretRealDeclarat", "labelRo": "Preț declarat real", "labelEn": "Declared price is the real price", "type": "select", "order": 45, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "notificareAml", "labelRo": "Notificare AML", "labelEn": "AML notice", "type": "select", "order": 46, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "consimtamantDatePersonale", "labelRo": "Consimțământ date personale", "labelEn": "Personal-data consent", "type": "select", "order": 47, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "preemptiuneTerenAgricol", "labelRo": "Preempțiune teren agricol", "labelEn": "Agricultural pre-emption", "type": "select", "order": 48, "aiHint": "formalitățile de preempțiune pentru teren extravilan", "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "INDEPLINITA", "labelRo": "Îndeplinită", "labelEn": "Completed"}, {"value": "NU_E_CAZUL", "labelRo": "Nu e cazul", "labelEn": "Not applicable"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "preemptiunePadure", "labelRo": "Preempțiune pădure", "labelEn": "Forest pre-emption", "type": "select", "order": 49, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "INDEPLINITA", "labelRo": "Îndeplinită", "labelEn": "Completed"}, {"value": "NU_E_CAZUL", "labelRo": "Nu e cazul", "labelEn": "Not applicable"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "taxeLocaleLaZi", "labelRo": "Taxe locale la zi", "labelEn": "Local taxes current", "type": "select", "order": 50, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "taxeLocalePlatiteDe", "labelRo": "Plătitor taxe locale", "labelEn": "Local taxes paid by", "type": "select", "order": 51, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "VANZATOR", "labelRo": "Vânzător", "labelEn": "Seller"}, {"value": "CUMPARATOR", "labelRo": "Cumpărător", "labelEn": "Buyer"}, {"value": "AMBELE", "labelRo": "Ambele părți", "labelEn": "Both parties"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "cheltuieliPerfectare", "labelRo": "Cheltuieli perfectare", "labelEn": "Closing costs borne by", "type": "select", "order": 52, "aiHint": null, "groupRo": "Conformitate și formalități", "groupEn": "Compliance and formalities", "tabRo": "Conformitate", "tabEn": "Compliance", "options": [{"value": "VANZATOR", "labelRo": "Vânzător", "labelEn": "Seller"}, {"value": "CUMPARATOR", "labelRo": "Cumpărător", "labelEn": "Buyer"}, {"value": "AMBELE", "labelRo": "Ambele părți", "labelEn": "Both parties"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]}
]
$cvc$::jsonb
 WHERE key = 'CONTRACT_VANZARE';

-- ── „Act Adițional" — 20 fields over 2 notebook tabs ──────────────────
UPDATE lookup_document_type
   SET template_fields = $act$
[
  {"key": "onorariuNotarial", "labelRo": "Onorariu notarial", "labelEn": "Notary fee", "type": "number", "order": 0, "aiHint": "onorariul cu TVA inclus, doar cifre", "groupRo": "Taxe și onorarii", "groupEn": "Fees", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "actParinteNumar", "labelRo": "Nr. act părinte", "labelEn": "Parent instrument no.", "type": "text", "order": 1, "aiHint": "numărul încheierii de autentificare a actului completat, doar numărul", "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "actParinteData", "labelRo": "Data act părinte", "labelEn": "Parent instrument date", "type": "date", "order": 2, "aiHint": "data autentificării actului completat", "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "actParinteNotariat", "labelRo": "Notariat act părinte", "labelEn": "Parent notary office", "type": "text", "order": 3, "aiHint": "biroul notarial care a autentificat actul completat, cum e scris pe act", "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "actParinteTip", "labelRo": "Tip act părinte", "labelEn": "Parent instrument type", "type": "select", "order": 4, "aiHint": null, "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": [{"value": "CONTRACT_VANZARE", "labelRo": "Contract de vânzare", "labelEn": "Sale contract"}, {"value": "ACT_PARTAJ", "labelRo": "Act de partaj", "labelEn": "Partition deed"}, {"value": "ACT_DONATIE", "labelRo": "Act de donație", "labelEn": "Donation deed"}, {"value": "ALTUL", "labelRo": "Alt act", "labelEn": "Other instrument"}]},
  {"key": "motivCompletare", "labelRo": "Motiv completare", "labelEn": "Reason for the supplement", "type": "textarea", "order": 5, "aiHint": "de ce a fost nevoie de completare, pe scurt și în termenii actului — «lipsă certificat de sarcini, intabulare refuzată»", "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "temeiLegalCompletare", "labelRo": "Temei legal completare", "labelEn": "Legal basis of the supplement", "type": "text", "order": 6, "aiHint": "articolul și legea invocate pentru completare — «art. N alin. N Legea N/aaaa»", "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "efectUrmarit", "labelRo": "Efect urmărit", "labelEn": "Intended effect", "type": "select", "order": 7, "aiHint": null, "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": [{"value": "INTABULARE", "labelRo": "Deblocarea intabulării", "labelEn": "Unblocking land-book registration"}, {"value": "RECTIFICARE", "labelRo": "Rectificarea actului", "labelEn": "Correcting the instrument"}, {"value": "COMPLETARE_CLAUZE", "labelRo": "Completarea clauzelor", "labelEn": "Supplementing the clauses"}, {"value": "ALTUL", "labelRo": "Alt efect", "labelEn": "Other effect"}]},
  {"key": "pretNeschimbat", "labelRo": "Preț neschimbat", "labelEn": "Price unchanged", "type": "select", "order": 8, "aiHint": null, "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": [{"value": "DA", "labelRo": "Da", "labelEn": "Yes"}, {"value": "NU", "labelRo": "Nu", "labelEn": "No"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}]},
  {"key": "calitateExemplar", "labelRo": "Calitate exemplar", "labelEn": "Copy status", "type": "select", "order": 9, "aiHint": null, "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": [{"value": "ORIGINAL", "labelRo": "Original", "labelEn": "Original"}, {"value": "DUPLICAT", "labelRo": "Duplicat", "labelEn": "Duplicate"}, {"value": "COPIE_LEGALIZATA", "labelRo": "Copie legalizată", "labelEn": "Certified copy"}]},
  {"key": "exemplareEmise", "labelRo": "Exemplare emise", "labelEn": "Originals issued", "type": "text", "order": 10, "aiHint": "numărul de exemplare și câte au rămas părților — «1 original și 7 duplicate, din care 6 părților»", "groupRo": "Act părinte", "groupEn": "Parent instrument", "tabRo": "Act adițional", "tabEn": "Supplement", "options": null},
  {"key": "liberDeSarcini", "labelRo": "Liber de sarcini", "labelEn": "Free of encumbrances", "type": "select", "order": 11, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "faraServituti", "labelRo": "Lipsă servituți", "labelEn": "Free of easements", "type": "select", "order": 12, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "nedezmembratNealipit", "labelRo": "Nedezmembrat și nealipit", "labelEn": "Not split and not merged", "type": "select", "order": 13, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "nearendat", "labelRo": "Nearendat", "labelEn": "Not leased", "type": "select", "order": 14, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "consimtamantRadiere", "labelRo": "Consimțământ radiere", "labelEn": "Consent to radiation", "type": "select", "order": 15, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "taxeLocaleLaZi", "labelRo": "Taxe locale la zi", "labelEn": "Local taxes current", "type": "select", "order": 16, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "notificareAml", "labelRo": "Notificare AML", "labelEn": "AML notice", "type": "select", "order": 17, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "consimtamantDatePersonale", "labelRo": "Consimțământ date personale", "labelEn": "Personal-data consent", "type": "select", "order": 18, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]},
  {"key": "celelalteClauzeNemodificate", "labelRo": "Celelalte clauze nemodificate", "labelEn": "Remaining parent clauses unchanged", "type": "select", "order": 19, "aiHint": null, "groupRo": "Clauze completate", "groupEn": "Supplemented clauses", "tabRo": "Clauze adăugate", "tabEn": "Added clauses", "options": [{"value": "AFIRMAT", "labelRo": "Afirmat", "labelEn": "Asserted"}, {"value": "NEMENTIONAT", "labelRo": "Nu e menționat", "labelEn": "Not stated"}, {"value": "EXCEPTIE", "labelRo": "Excepție", "labelEn": "Exception"}]}
]
$act$::jsonb
 WHERE key = 'ACT_ADITIONAL';

DO $do$
DECLARE
  cvc_count int;
  act_count int;
BEGIN
  SELECT jsonb_array_length(template_fields) INTO cvc_count
    FROM lookup_document_type WHERE key = 'CONTRACT_VANZARE';
  SELECT jsonb_array_length(template_fields) INTO act_count
    FROM lookup_document_type WHERE key = 'ACT_ADITIONAL';
  -- A missing row leaves a NULL count, not a zero: the UPDATE matched nothing
  -- and the form was never written, which is the case most worth shouting
  -- about. IS DISTINCT FROM catches it; `<>` would not.
  IF cvc_count IS DISTINCT FROM 53 OR act_count IS DISTINCT FROM 20 THEN
    RAISE EXCEPTION 'migration_085: expected 53 / 20 template fields on CONTRACT_VANZARE / ACT_ADITIONAL, got % / %',
      cvc_count, act_count;
  END IF;
  RAISE NOTICE 'migration_085: CONTRACT_VANZARE now carries % template field(s), ACT_ADITIONAL %.',
    cvc_count, act_count;
END $do$;
