/**
 * Provenance value set — single source of truth  (Slice #21.07.Import)
 *
 * `entity_metadata.provenance` records HOW an entity entered the system.
 * Before this slice the list was hardcoded in three separate components, and
 * two of those copies had drifted out of sync with the DB CHECK constraint
 * (`chk_em_provenance`), so their filter dropdowns offered values that could
 * never match a stored row. Every consumer now imports from here.
 *
 * The list is deliberately a FIXED, code-defined enum rather than an
 * admin-managed lookup table: the automatic-assignment rules in
 * `provenance-rules.ts` reference these codes directly, so a runtime-deletable
 * row would orphan a coded rule.
 *
 * Changing the list is a three-part change that must land together:
 *   1. this array,
 *   2. the `chk_em_provenance` CHECK constraint (a new migration),
 *   3. the label + statement keys in `messages/{en-GB,ro-RO}.json` under
 *      `shared.entityMetadata.provenance` and `globalSearch.provenanceValues`.
 *
 * Client-safe: pure constants, no DB or server-only imports.
 */

export const PROVENANCE_VALUES = [
  /** Typed in by a user through an "Add new" form. */
  "MANUAL",
  /** Created from a graphics file — a scan or a photo. */
  "IMAGE",
  /** Created from a PDF, Word or plain-text file, stored as-is. */
  "DOC_FILE",
  /** Created from a cadastral Stereo 70 coordinate file (.txt). */
  "COORDINATE_FILE",
  /** Generated by an algorithm (e.g. the Calculation / division feature). */
  "ALGORITHM",
  /** Extracted by an AI model from an image or document. */
  "AI_INTERPRETED",
  /** Arrived from an external system or data feed. */
  "EXTERNAL_FEED",
] as const;

export type ProvenanceCode = (typeof PROVENANCE_VALUES)[number];

/** Runtime guard — use on any value crossing the network boundary. */
export function isProvenanceCode(value: unknown): value is ProvenanceCode {
  return (
    typeof value === "string" &&
    (PROVENANCE_VALUES as readonly string[]).includes(value)
  );
}

/**
 * camelCase i18n key for a code, matching the label keys under
 * `shared.entityMetadata.provenance` (e.g. "DOC_FILE" -> "docFile") and,
 * capitalised, the `statement*` keys (e.g. "statementDocFile").
 */
export function provenanceI18nKey(code: ProvenanceCode): string {
  return code.toLowerCase().replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Read an optional `provenance` field off a create-request body.
 *
 * Deliberately NOT part of the entity create Zod schemas: those objects are
 * passed straight into createProperty / createDocument / createNaturalPerson /
 * createJudicialPerson, and provenance does not live on those tables - it
 * belongs to entity_metadata, written after the entity exists. Reading it
 * separately keeps the create input types clean.
 *
 * Returns null for a missing, malformed or unknown value; the caller then
 * simply records no provenance, exactly as before this slice.
 */
export function provenanceFromRequestBody(body: unknown): ProvenanceCode | null {
  if (typeof body !== "object" || body === null) return null;
  const value = (body as { provenance?: unknown }).provenance;
  return isProvenanceCode(value) ? value : null;
}
